COMPONENT=Reconfig_LightAppC
CFLAGS += -I$(TOSDIR)/lib/net \
          -I$(TOSDIR)/lib/net/le \
          -I$(TOSDIR)/lib/net/ctp
PFLAGS += -I$(TOSDIR)/lib/printf
BOOTLOADER = tosboot
include $(MAKERULES)